image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  #- build-web
  - build-prod

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build job:
  stage: build-prod
  script:
  # nginx, test configuration and exit.
  #- nginx -v
  #- nginx -t
  - TMPTAG=$(date +%Y%m%d-%H%M)
  - docker build --pull -t $CI_REGISTRY_IMAGE:latest .
  - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$TMPTAG
  - docker push $CI_REGISTRY_IMAGE:$TMPTAG
  - docker tag $CI_REGISTRY_IMAGE:latest
  #- docker images
